Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "gdx-backend-bytecoder-wasm-llvm-install-test"
  config.vm.provision "shell", inline: "apt-get update"
end
